
const countrys: { value: string }[] = [];
countrys.push({ value: '中国' })
countrys.push({ value: 'Afghanistan' })
countrys.push({ value: 'Aland Islands' })
countrys.push({ value: 'Albania' })
countrys.push({ value: 'Algeria' })
countrys.push({ value: 'American Samoa' })
countrys.push({ value: 'Andorra' })
countrys.push({ value: 'Angola' })
countrys.push({ value: 'Anguilla' })
countrys.push({ value: 'Antigua and Barbuda' })
countrys.push({ value: 'Argentina' })
countrys.push({ value: 'Armenia' })
countrys.push({ value: 'Aruba' })
countrys.push({ value: 'Australia' })
countrys.push({ value: 'Austria' })
countrys.push({ value: 'Azerbaijan' })
countrys.push({ value: 'Bangladesh' })
countrys.push({ value: 'Bahrain' })
countrys.push({ value: 'Bahamas' })
countrys.push({ value: 'Barbados' })
countrys.push({ value: 'Belarus' })
countrys.push({ value: 'Belgium' })
countrys.push({ value: 'Belize' })
countrys.push({ value: 'Benin' })
countrys.push({ value: 'Bermuda' })
countrys.push({ value: 'Bhutan' })
countrys.push({ value: 'Bolivia' })
countrys.push({ value: 'Bosnia and Herzegovina' })
countrys.push({ value: 'Botswana' })
countrys.push({ value: 'Bouvet Island' })
countrys.push({ value: 'Brazil' })
countrys.push({ value: 'Brunei' })
countrys.push({ value: 'Bulgaria' })
countrys.push({ value: 'Burkina Faso' })
countrys.push({ value: 'Burundi' })
countrys.push({ value: 'Cambodia' })
countrys.push({ value: 'Cameroon' })
countrys.push({ value: 'Canada' })
countrys.push({ value: 'Cape Verde' })
countrys.push({ value: 'Central African Republic' })
countrys.push({ value: 'Chad' })
countrys.push({ value: 'Chile' })
countrys.push({ value: 'Christmas Islands' })
countrys.push({ value: 'Cocos (keeling) Islands' })
countrys.push({ value: 'Colombia' })
countrys.push({ value: 'Comoros' })
countrys.push({ value: 'Congo (Congo-Kinshasa)' })
countrys.push({ value: 'Congo' })
countrys.push({ value: 'Cook Islands' })
countrys.push({ value: 'Costa Rica' })
countrys.push({ value: 'Cote D\'Ivoire' })
countrys.push({ value: 'Croatia' })
countrys.push({ value: 'Cuba' })
countrys.push({ value: 'Czech' })
countrys.push({ value: 'Cyprus' })
countrys.push({ value: 'Denmark' })
countrys.push({ value: 'Djibouti' })
countrys.push({ value: 'Dominica' })
countrys.push({ value: 'Ecuador' })
countrys.push({ value: 'Egypt' })
countrys.push({ value: 'Equatorial Guinea' })
countrys.push({ value: 'Eritrea' })
countrys.push({ value: 'Estonia' })
countrys.push({ value: 'Ethiopia' })
countrys.push({ value: 'Faroe Islands' })
countrys.push({ value: 'Fiji' })
countrys.push({ value: 'Finland' })
countrys.push({ value: 'France' })
countrys.push({ value: 'MetropolitanFrance' })
countrys.push({ value: 'French Guiana' })
countrys.push({ value: 'French Polynesia' })
countrys.push({ value: 'Gabon' })
countrys.push({ value: 'Gambia' })
countrys.push({ value: 'Georgia' })
countrys.push({ value: 'Germany' })
countrys.push({ value: 'Ghana' })
countrys.push({ value: 'Gibraltar' })
countrys.push({ value: 'Greece' })
countrys.push({ value: 'Grenada' })
countrys.push({ value: 'Guadeloupe' })
countrys.push({ value: 'Guam' })
countrys.push({ value: 'Guatemala' })
countrys.push({ value: 'Guernsey' })
countrys.push({ value: 'Guinea-Bissau' })
countrys.push({ value: 'Guinea' })
countrys.push({ value: 'Guyana' })
countrys.push({ value: 'Haiti' })
countrys.push({ value: 'Honduras' })
countrys.push({ value: 'Hungary' })
countrys.push({ value: 'Iceland' })
countrys.push({ value: 'India' })
countrys.push({ value: 'Indonesia' })
countrys.push({ value: 'Iran' })
countrys.push({ value: 'Iraq' })
countrys.push({ value: 'Ireland' })
countrys.push({ value: 'Isle of Man' })
countrys.push({ value: 'Israel' })
countrys.push({ value: 'Italy' })
countrys.push({ value: 'Jamaica' })
countrys.push({ value: 'Japan' })
countrys.push({ value: 'Jersey' })
countrys.push({ value: 'Jordan' })
countrys.push({ value: 'Kazakhstan' })
countrys.push({ value: 'Kenya' })
countrys.push({ value: 'Kiribati' })
countrys.push({ value: 'Korea (South)' })
countrys.push({ value: 'Korea (North)' })
countrys.push({ value: 'Kuwait' })
countrys.push({ value: 'Kyrgyzstan' })
countrys.push({ value: 'Laos' })
countrys.push({ value: 'Latvia' })
countrys.push({ value: 'Lebanon' })
countrys.push({ value: 'Lesotho' })
countrys.push({ value: 'Liberia' })
countrys.push({ value: 'Libya' })
countrys.push({ value: 'Liechtenstein' })
countrys.push({ value: 'Lithuania' })
countrys.push({ value: 'Luxembourg' })
countrys.push({ value: 'Macedonia' })
countrys.push({ value: 'Malawi' })
countrys.push({ value: 'Malaysia' })
countrys.push({ value: 'Madagascar' })
countrys.push({ value: 'Maldives' })
countrys.push({ value: 'Mali' })
countrys.push({ value: 'Malta' })
countrys.push({ value: 'Marshall Islands' })
countrys.push({ value: 'Martinique' })
countrys.push({ value: 'Mauritania' })
countrys.push({ value: 'Mauritius' })
countrys.push({ value: 'Mayotte' })
countrys.push({ value: 'Mexico' })
countrys.push({ value: 'Micronesia' })
countrys.push({ value: 'Moldova' })
countrys.push({ value: 'Monaco' })
countrys.push({ value: 'Mongolia' })
countrys.push({ value: 'Montenegro' })
countrys.push({ value: 'Montserrat' })
countrys.push({ value: 'Morocco' })
countrys.push({ value: 'Mozambique' })
countrys.push({ value: 'Myanmar' })
countrys.push({ value: 'Namibia' })
countrys.push({ value: 'Nauru' })
countrys.push({ value: 'Nepal' })
countrys.push({ value: 'Netherlands' })
countrys.push({ value: 'New Caledonia' })
countrys.push({ value: 'New Zealand' })
countrys.push({ value: 'Nicaragua' })
countrys.push({ value: 'Niger' })
countrys.push({ value: 'Nigeria' })
countrys.push({ value: 'Niue' })
countrys.push({ value: 'Norfolk Island' })
countrys.push({ value: 'Norway' })
countrys.push({ value: 'Oman' })
countrys.push({ value: 'Pakistan' })
countrys.push({ value: 'Palau' })
countrys.push({ value: 'Palestine' })
countrys.push({ value: 'Panama' })
countrys.push({ value: 'Papua New Guinea' })
countrys.push({ value: 'Peru' })
countrys.push({ value: 'Philippines' })
countrys.push({ value: 'Pitcairn Islands' })
countrys.push({ value: 'Poland' })
countrys.push({ value: 'Portugal' })
countrys.push({ value: 'Puerto Rico' })
countrys.push({ value: 'Qatar' })
countrys.push({ value: 'Reunion' })
countrys.push({ value: 'Romania' })
countrys.push({ value: 'Rwanda' })
countrys.push({ value: 'Russian Federation' })
countrys.push({ value: 'Saint Helena' })
countrys.push({ value: 'Saint Kitts-Nevis' })
countrys.push({ value: 'Saint Lucia' })
countrys.push({ value: 'Saint Vincent and the Grenadines' })
countrys.push({ value: 'El Salvador' })
countrys.push({ value: 'Samoa' })
countrys.push({ value: 'San Marino' })
countrys.push({ value: 'Sao Tome and Principe' })
countrys.push({ value: 'Saudi Arabia' })
countrys.push({ value: 'Senegal' })
countrys.push({ value: 'Seychelles' })
countrys.push({ value: 'Sierra Leone' })
countrys.push({ value: 'Singapore' })
countrys.push({ value: 'Serbia' })
countrys.push({ value: 'Slovakia' })
countrys.push({ value: 'Slovenia' })
countrys.push({ value: 'Solomon Islands' })
countrys.push({ value: 'Somalia' })
countrys.push({ value: 'South Africa' })
countrys.push({ value: 'Spain' })
countrys.push({ value: 'Sri Lanka' })
countrys.push({ value: 'Sudan' })
countrys.push({ value: 'Suriname' })
countrys.push({ value: 'Swaziland' })
countrys.push({ value: 'Sweden' })
countrys.push({ value: 'Switzerland' })
countrys.push({ value: 'Syria' })
countrys.push({ value: 'Tajikistan' })
countrys.push({ value: 'Tanzania' })
countrys.push({ value: 'Thailand' })
countrys.push({ value: 'Trinidad and Tobago' })
countrys.push({ value: 'Timor-Leste' })
countrys.push({ value: 'Togo' })
countrys.push({ value: 'Tokelau' })
countrys.push({ value: 'Tonga' })
countrys.push({ value: 'Tunisia' })
countrys.push({ value: 'Turkey' })
countrys.push({ value: 'Turkmenistan' })
countrys.push({ value: 'Tuvalu' })
countrys.push({ value: 'Uganda' })
countrys.push({ value: 'Ukraine' })
countrys.push({ value: 'United Arab Emirates' })
countrys.push({ value: 'United Kingdom' })
countrys.push({ value: 'United States' })
countrys.push({ value: 'Uruguay' })
countrys.push({ value: 'Uzbekistan' })
countrys.push({ value: 'Vanuatu' })
countrys.push({ value: 'Vatican City' })
countrys.push({ value: 'Venezuela' })
countrys.push({ value: 'Vietnam' })
countrys.push({ value: 'Wallis and Futuna' })
countrys.push({ value: 'Western Sahara' })
countrys.push({ value: 'Yemen' })
countrys.push({ value: 'Yugoslavia' })
countrys.push({ value: 'Zambia' })
countrys.push({ value: 'Zimbabwe' })

export default countrys;